def country_code_to_name():
    COUNTRY_CODE_TO_NAME = {
        "AF": ["Afghanistan", "AF"],
        "AX": ["Åland Islands", "AX"],
        "AL": ["Albania", "AL"],
        "DZ": ["Algeria", "DZ"],
        "AS": ["American Samoa", "AS"],
        "AD": ["Andorra", "AD"],
        "AO": ["Angola", "AO"],
        "AI": ["Anguilla", "AI"],
        "AQ": ["Antarctica", "AQ"],
        "AG": ["Antigua and Barbuda", "Antigua", "AG"],
        "AR": ["Argentina", "AR"],
        "AM": ["Armenia", "AM"],
        "AW": ["Aruba", "AW"],
        "AU": ["Australia", "AU"],
        "AT": ["Austria", "AT"],
        "AZ": ["Azerbaijan", "AZ"],
        "BS": ["Bahamas", "The Bahamas", "BS"],
        "BH": ["Bahrain", "BH"],
        "BD": ["Bangladesh", "BD"],
        "BB": ["Barbados", "BB"],
        "BY": ["Belarus", "BY"],
        "BE": ["Belgium", "BE"],
        "BZ": ["Belize", "BZ"],
        "BJ": ["Benin", "BJ"],
        "BM": ["Bermuda", "BM"],
        "BT": ["Bhutan", "BT"],
        "BO": ["Bolivia", "BO"],
        "BQ": ["Bonaire, Sint Eustatius and Saba", "Bonaire", "BQ"],
        "BA": ["Bosnia and Herzegovina", "Bosnia", "BA"],
        "BW": ["Botswana", "BW"],
        "BV": ["Bouvet Island", "BV"],
        "BR": ["Brazil", "BR"],
        "IO": ["British Indian Ocean Territory", "IO"],
        "BN": ["Brunei Darussalam", "Brunei", "BN"],
        "BG": ["Bulgaria", "BG"],
        "BF": ["Burkina Faso", "BF"],
        "BI": ["Burundi", "BI"],
        "CV": ["Cabo Verde", "Cape Verde", "CV"],
        "KH": ["Cambodia", "KH"],
        "CM": ["Cameroon", "CM"],
        "CA": ["Canada", "CA"],
        "KY": ["Cayman Islands", "KY"],
        "CF": ["Central African Republic", "CAR", "CF"],
        "TD": ["Chad", "TD"],
        "CL": ["Chile", "CL"],
        "CN": ["China", "CN"],
        "CX": ["Christmas Island", "CX"],
        "CC": ["Cocos (Keeling) Islands", "CC"],
        "CO": ["Colombia", "CO"],
        "KM": ["Comoros", "KM"],
        "CG": ["Congo", "CG"],
        "CD": ["Congo (Democratic Republic of the)", "DRC", "CD"],
        "CK": ["Cook Islands", "CK"],
        "CR": ["Costa Rica", "CR"],
        "HR": ["Croatia", "HR"],
        "CU": ["Cuba", "CU"],
        "CW": ["Curaçao", "CW"],
        "CY": ["Cyprus", "CY"],
        "CZ": ["Czechia", "Czech Republic", "CZ"],
        "CI": ["Côte d'Ivoire", "Ivory Coast", "CI"],
        "DK": ["Denmark", "DK"],
        "DJ": ["Djibouti", "DJ"],
        "DM": ["Dominica", "DM"],
        "DO": ["Dominican Republic", "DO"],
        "EC": ["Ecuador", "EC"],
        "EG": ["Egypt", "EG"],
        "SV": ["El Salvador", "SV"],
        "GQ": ["Equatorial Guinea", "GQ"],
        "ER": ["Eritrea", "ER"],
        "EE": ["Estonia", "EE"],
        "SZ": ["Eswatini", "Swaziland", "SZ"],
        "ET": ["Ethiopia", "ET"],
        "FK": ["Falkland Islands", "FK"],
        "FO": ["Faroe Islands", "FO"],
        "FJ": ["Fiji", "FJ"],
        "FI": ["Finland", "FI"],
        "FR": ["France", "FR"],
        "GF": ["French Guiana", "GF"],
        "PF": ["French Polynesia", "PF"],
        "TF": ["French Southern Territories", "TF"],
        "GA": ["Gabon", "GA"],
        "GM": ["Gambia", "The Gambia", "GM"],
        "GE": ["Georgia", "GE"],
        "DE": ["Germany", "DE"],
        "GH": ["Ghana", "GH"],
        "GI": ["Gibraltar", "GI"],
        "GR": ["Greece", "GR"],
        "GL": ["Greenland", "GL"],
        "GD": ["Grenada", "GD"],
        "GP": ["Guadeloupe", "GP"],
        "GU": ["Guam", "GU"],
        "GT": ["Guatemala", "GT"],
        "GG": ["Guernsey", "GG"],
        "GN": ["Guinea", "GN"],
        "GW": ["Guinea-Bissau", "GW"],
        "GY": ["Guyana", "GY"],
        "HT": ["Haiti", "HT"],
        "HM": ["Heard Island and McDonald Islands", "HM"],
        "VA": ["Holy See", "Vatican", "VA"],
        "HN": ["Honduras", "HN"],
        "HK": ["Hong Kong", "HK"],
        "HU": ["Hungary", "HU"],
        "IS": ["Iceland", "IS"],
        "IN": ["India", "IN"],
        "ID": ["Indonesia", "ID"],
        "IR": ["Iran", "IR"],
        "IQ": ["Iraq", "IQ"],
        "IE": ["Ireland", "IE"],
        "IM": ["Isle of Man", "IM"],
        "IL": ["Israel", "IL"],
        "IT": ["Italy", "IT"],
        "JM": ["Jamaica", "JM"],
        "JP": ["Japan", "JP"],
        "JE": ["Jersey", "JE"],
        "JO": ["Jordan", "JO"],
        "KZ": ["Kazakhstan", "KZ"],
        "KE": ["Kenya", "KE"],
        "KI": ["Kiribati", "KI"],
        "KP": ["Korea (Democratic People's Republic of)", "North Korea", "KP"],
        "KR": ["Korea (Republic of)", "South Korea", "KR"],
        "KW": ["Kuwait", "KW"],
        "KG": ["Kyrgyzstan", "KG"],
        "LA": ["Lao People's Democratic Republic", "Laos", "LA"],
    "LV": ["Latvia", "Republic of Latvia", "LV"],
    "LB": ["Lebanon", "Lebanese Republic", "LB"],
    "LS": ["Lesotho", "Kingdom of Lesotho", "LS"],
    "LR": ["Liberia", "Republic of Liberia", "LR"],
    "LY": ["Libya", "State of Libya", "LY"],
    "LI": ["Liechtenstein", "Principality of Liechtenstein", "LI"],
    "LT": ["Lithuania", "Republic of Lithuania", "LT"],
    "LU": ["Luxembourg", "Grand Duchy of Luxembourg", "LU"],
    "MO": ["Macao", "Macau", "MO"],
    "MG": ["Madagascar", "Republic of Madagascar", "MG"],
    "MW": ["Malawi", "Republic of Malawi", "MW"],
    "MY": ["Malaysia", "Malaysia", "MY"],
    "MV": ["Maldives", "Republic of Maldives", "MV"],
    "ML": ["Mali", "Republic of Mali", "ML"],
    "MT": ["Malta", "Republic of Malta", "MT"],
    "MH": ["Marshall Islands", "Republic of the Marshall Islands", "MH"],
    "MQ": ["Martinique", "Martinique", "MQ"],
    "MR": ["Mauritania", "Islamic Republic of Mauritania", "MR"],
    "MU": ["Mauritius", "Republic of Mauritius", "MU"],
    "YT": ["Mayotte", "Mayotte", "YT"],
    "MX": ["Mexico", "United Mexican States", "MX"],
    "FM": ["Micronesia (Federated States of)", "Federated States of Micronesia", "FM"],
    "MD": ["Moldova", "Republic of Moldova", "MD"],
    "MC": ["Monaco", "Principality of Monaco", "MC"],
    "MN": ["Mongolia", "State of Mongolia", "MN"],
    "ME": ["Montenegro", "Montenegro", "ME"],
    "MS": ["Montserrat", "Montserrat", "MS"],
    "MA": ["Morocco", "Kingdom of Morocco", "MA"],
    "MZ": ["Mozambique", "Republic of Mozambique", "MZ"],
    "MM": ["Myanmar", "Republic of the Union of Myanmar", "MM"],
    "NA": ["Namibia", "Republic of Namibia", "NA"],
    "NR": ["Nauru", "Republic of Nauru", "NR"],
    "NP": ["Nepal", "Federal Democratic Republic of Nepal", "NP"],
    "NL": ["Netherlands", "Kingdom of the Netherlands", "NL"],
    "NC": ["New Caledonia", "New Caledonia", "NC"],
    "NZ": ["New Zealand", "Aotearoa New Zealand", "NZ"],
    "NI": ["Nicaragua", "Republic of Nicaragua", "NI"],
    "NE": ["Niger", "Republic of the Niger", "NE"],
    "NG": ["Nigeria", "Federal Republic of Nigeria", "NG"],
    "NU": ["Niue", "Niue", "NU"],
    "NF": ["Norfolk Island", "Norfolk Island", "NF"],
    "MP": ["Northern Mariana Islands", "Commonwealth of the Northern Mariana Islands", "MP"],
    "NO": ["Norway", "Kingdom of Norway", "NO"],
    "OM": ["Oman", "Sultanate of Oman", "OM"],
    "PK": ["Pakistan", "Islamic Republic of Pakistan", "PK"],
    "PW": ["Palau", "Republic of Palau", "PW"],
    "PS": ["Palestine, State of", "State of Palestine", "PS"],
    "PA": ["Panama", "Republic of Panama", "PA"],
    "PG": ["Papua New Guinea", "Independent State of Papua New Guinea", "PG"],
    "PY": ["Paraguay", "Republic of Paraguay", "PY"],
    "PE": ["Peru", "Republic of Peru", "PE"],
    "PH": ["Philippines", "Republic of the Philippines", "PH"],
    "PN": ["Pitcairn", "Pitcairn Islands", "PN"],
    "PL": ["Poland", "Republic of Poland", "PL"],
    "PT": ["Portugal", "Portuguese Republic", "PT"],
    "PR": ["Puerto Rico", "Commonwealth of Puerto Rico", "PR"],
    "QA": ["Qatar", "State of Qatar", "QA"],
    "MK": ["Republic of North Macedonia", "North Macedonia", "MK"],
    "RO": ["Romania", "Romania", "RO"],
    "RU": ["Russian Federation", "Russia", "RU"],
    "RW": ["Rwanda", "Republic of Rwanda", "RW"],
    "RE": ["Réunion", "Réunion", "RE"],
    "BL": ["Saint Barthélemy", "Saint Barthélemy", "BL"],
    "SH": ["Saint Helena, Ascension and Tristan da Cunha", "Saint Helena", "Ascension Island", "Tristan da Cunha", "SH"],
    "KN": ["Saint Kitts and Nevis", "Federation of Saint Kitts and Nevis", "KN"],
    "LC": ["Saint Lucia", "Saint Lucia", "LC"],
    "MF": ["Saint Martin (French part)", "Saint Martin", "MF"],
    "PM": ["Saint Pierre and Miquelon", "Saint Pierre and Miquelon", "PM"],
    "VC": ["Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines", "VC"],
    "WS": ["Samoa", "Independent State of Samoa", "WS"],
    "SM": ["San Marino", "Republic of San Marino", "SM"],
    "ST": ["Sao Tome and Principe", "Democratic Republic of Sao Tome and Principe", "ST"],
    "SA": ["Saudi Arabia", "Kingdom of Saudi Arabia", "SA"],
    "SN": ["Senegal", "Republic of Senegal", "SN"],
    "RS": ["Serbia", "Republic of Serbia", "RS"],
    "SC": ["Seychelles", "Republic of Seychelles", "SC"],
    "SL": ["Sierra Leone", "Republic of Sierra Leone", "SL"],
    "SG": ["Singapore", "Republic of Singapore", "SG"],
    "SX": ["Sint Maarten (Dutch part)", "Sint Maarten", "SX"],
    "SK": ["Slovakia", "Slovak Republic", "SK"],
    "SI": ["Slovenia", "Republic of Slovenia", "SI"],
    "SB": ["Solomon Islands", "Solomon Islands", "SB"],
    "SO": ["Somalia", "Federal Republic of Somalia", "SO"],
    "ZA": ["South Africa", "Republic of South Africa", "ZA"],
    "GS": ["South Georgia and the South Sandwich Islands", "South Georgia", "South Sandwich Islands", "GS"],
    "SS": ["South Sudan", "Republic of South Sudan", "SS"],
    "ES": ["Spain", "Kingdom of Spain", "ES"],
    "LK": ["Sri Lanka", "Democratic Socialist Republic of Sri Lanka", "LK"],
    "SD": ["Sudan", "Republic of the Sudan", "SD"],
    "SR": ["Suriname", "Republic of Suriname", "SR"],
    "SJ": ["Svalbard and Jan Mayen", "Svalbard", "Jan Mayen", "SJ"],
    "SE": ["Sweden", "Kingdom of Sweden", "SE"],
    "CH": ["Switzerland", "Swiss Confederation", "CH"],
    "SY": ["Syrian Arab Republic", "Syria", "SY"],
    "TW": ["Taiwan (Province of China)", "Taiwan", "Republic of China", "TW"],
    "TJ": ["Tajikistan", "Republic of Tajikistan", "TJ"],
    "TZ": ["Tanzania", "United Republic of Tanzania", "TZ"],
    "TH": ["Thailand", "Kingdom of Thailand", "TH"],
    "TL": ["Timor-Leste", "East Timor", "TL"],
    "TG": ["Togo", "Togolese Republic", "TG"],
    "TK": ["Tokelau", "Tokelau", "TK"],
    "TO": ["Tonga", "Kingdom of Tonga", "TO"],
    "TT": ["Trinidad and Tobago", "Republic of Trinidad and Tobago", "TT"],
    "TN": ["Tunisia", "Republic of Tunisia", "TN"],
    "TR": ["Turkey", "Republic of Turkey", "TR"],
    "TM": ["Turkmenistan", "Turkmenistan", "TM"],
    "TC": ["Turks and Caicos Islands", "Turks and Caicos", "TC"],
    "TV": ["Tuvalu", "Tuvalu", "TV"],
    "UG": ["Uganda", "Republic of Uganda", "UG"],
    "UA": ["Ukraine", "Ukraine", "UA"],
    "AE": ["United Arab Emirates", "UAE", "AE"],
    "GB": ["United Kingdom", "UK", "Great Britain", "GB"],
    "US": ["United States", "USA", "United States of America", "US"],
    "UM": ["United States Minor Outlying Islands", "US Minor Outlying Islands", "UM"],
    "UY": ["Uruguay", "Oriental Republic of Uruguay", "UY"],
    "UZ": ["Uzbekistan", "Republic of Uzbekistan", "UZ"],
    "VU": ["Vanuatu", "Republic of Vanuatu", "VU"],
    "VE": ["Venezuela", "Bolivarian Republic of Venezuela", "VE"],
    "VN": ["Viet Nam", "Vietnam", "VN"],
    "VG": ["Virgin Islands (British)", "British Virgin Islands", "VG"],
    "VI": ["Virgin Islands (U.S.)", "U.S. Virgin Islands", "VI"],
    "WF": ["Wallis and Futuna", "Wallis and Futuna Islands", "WF"],
    "EH": ["Western Sahara", "Sahrawi Arab Democratic Republic", "EH"],
    "YE": ["Yemen", "Republic of Yemen", "YE"],
    "ZM": ["Zambia", "Republic of Zambia", "ZM"],
    "ZW": ["Zimbabwe", "Republic of Zimbabwe", "ZW"]
}

    return COUNTRY_CODE_TO_NAME

